SELECT
    "CITY",
  "NEIGHBOURHOOD_CLEANSED",
  MD5(CONCAT(TRIM(LOWER("NEIGHBOURHOOD_CLEANSED")), '|', TRIM(LOWER("CITY")))) AS neighbourhood_key
FROM {{ ref('l1_listings') }}
GROUP BY "CITY", "NEIGHBOURHOOD_CLEANSED"
ORDER BY "CITY", "NEIGHBOURHOOD_CLEANSED"