SELECT
  "CITY",
  "SNAPSHOT_DATE",
  MD5(CONCAT(TRIM(LOWER("CITY")), '|', CAST("SNAPSHOT_DATE" AS VARCHAR))) AS city_snapshot_key
FROM {{ ref('l1_reviews') }}
GROUP BY "CITY", "SNAPSHOT_DATE"
ORDER BY "CITY", "SNAPSHOT_DATE"