name: airbnb

profile: airbnb

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  airbnb:
    +schema: raw

models:
  airbnb:
    # Materialize staging models as views, and marts as tables
    l0:
      +schema: l0
      +materialized: view
    l1:
      +schema: l1
      +materialized: view
    l2:
      +schema: l2
      +materialized: table